<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataCleaning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Categorical Data

In [2]:
values = pd.Series([
    'apple' , 'orange' , 'apple' , 'apple'
] * 2)

In [3]:
values

,0
0,apple
1,orange
2,apple
3,apple
4,apple
5,orange
6,apple
7,apple


In [9]:
values.unique()

array(['apple', 'orange'], dtype=object)

In [7]:
values.value_counts()

,count
apple,6
orange,2


In [10]:
values = pd.Series([0 , 1 , 0 , 0] * 2)

In [11]:
dim = pd.Series(['apple' , 'orange'])

In [12]:
values

,0
0,0
1,1
2,0
3,0
4,0
5,1
6,0
7,0


In [13]:
dim

,0
0,apple
1,orange


In [15]:
dim.take(values)

,0
0,apple
1,orange
0,apple
0,apple
0,apple
1,orange
0,apple
0,apple


In [16]:
print('This representation is called categorical or dict encoded where the array of distinct values is called categories and integer values are catgory codes')

This representation is called categorical or dict encoded where the array of distinct values is called categories and integer values are catgory codes


In [17]:
fruits = ['apple' , 'orange' , 'apple' , 'apple'] * 2

In [18]:
N = len(fruits)

In [19]:
rng = np.random.default_rng(seed = 42)

In [25]:
df = pd.DataFrame(
    {
        'fruit' : fruits ,
        'basket_id' : np.arange(N) ,
        'count' : rng.integers(3 , 15 , size = N) ,
        'Weight' : rng.uniform(0 , 4 , size = N) ,
    } ,
    columns = ['basket_id' , 'fruit' , 'count' , 'weight']
)

In [26]:
df

,basket_id,fruit,count,weight
0,0,apple,12,NaN
1,1,orange,10,NaN
2,2,apple,7,NaN
3,3,apple,12,NaN
4,4,apple,9,NaN
5,5,orange,8,NaN
6,6,apple,8,NaN
7,7,apple,5,NaN


In [27]:
fruit_cat = df['fruit'].astype('category')

In [28]:
fruit_cat

,fruit
0,apple
1,orange
2,apple
3,apple
4,apple
5,orange
6,apple
7,apple


In [29]:
c = fruit_cat.array

In [31]:
print(type(c))

<class 'pandas.core.arrays.categorical.Categorical'>


In [32]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [33]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [34]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [35]:
df['fruit']

,fruit
0,apple
1,orange
2,apple
3,apple
4,apple
5,orange
6,apple
7,apple


In [36]:
my_cate = pd.Categorical(['foo' , 'bar' , 'baz' , 'foo' , 'bar'])

In [37]:
my_cate

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [38]:
dict(enumerate(my_cate.categories))

{0: 'bar', 1: 'baz', 2: 'foo'}

In [39]:
my_cate.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [40]:
cate = ['foo' , 'bar' , 'baz']
codes = [0 , 1 , 2 , 0 , 0 , 1]

In [41]:
my_cate_2 = pd.Categorical.from_codes(codes , cate)

In [42]:
my_cate_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [43]:
ordered_cat = pd.Categorical.from_codes(codes , cate , ordered = True)

In [46]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [47]:
my_cate_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [48]:
print('pd.Categprical.from_codes or just pd.Categorical or astype(Categorical) can be used to form Categorical Data having codes and Categories')

pd.Categprical.from_codes or just pd.Categorical or astype(Categorical) can be used to form Categorical Data having codes and Categories


In [49]:
print('as_ordered() or ordered = True can be used to make them ordered for view and ordered respectively')

as_ordered() or ordered = True can be used to make them ordered for view and ordered respectively


### Computations with Categories

In [50]:
draws = rng.standard_normal(1000)

In [51]:
draws[:5]

array([-0.42832782, -0.35213355,  0.53230919,  0.36544406,  0.41273261])

In [52]:
bins = pd.qcut(draws , 4)

In [53]:
bins

[(-0.694, 0.00618], (-0.694, 0.00618], (0.00618, 0.588], (0.00618, 0.588], (0.00618, 0.588], ..., (0.588, 3.179], (0.00618, 0.588], (0.00618, 0.588], (0.00618, 0.588], (0.588, 3.179]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.649, -0.694] < (-0.694, 0.00618] < (0.00618, 0.588] <
                                           (0.588, 3.179]]

In [54]:
bins = pd.qcut(draws , 4 , labels = ['Q1' , 'Q2' , 'Q3' , 'Q4'])

In [55]:
bins

['Q2', 'Q2', 'Q3', 'Q3', 'Q3', ..., 'Q4', 'Q3', 'Q3', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [56]:
bins.codes[:10]

array([1, 1, 2, 2, 2, 2, 3, 1, 1, 0], dtype=int8)

In [62]:
bins = pd.Series(bins , name = 'quartile')

In [63]:
bins.head()

,quartile
0,Q2
1,Q2
2,Q3
3,Q3
4,Q3


In [80]:
results = pd.Series(draws).groupby(bins , observed = False).agg(['count' , 'min' , 'max']).reset_index()

In [81]:
results

,quartile,count,min,max
0,Q1,250,-3.648413,-0.695943
1,Q2,250,-0.693506,0.006017
2,Q3,250,0.006339,0.587259
3,Q4,250,0.589547,3.178854


In [82]:
results['quartile']

,quartile
0,Q1
1,Q2
2,Q3
3,Q4


In [83]:
print("The 'quartile' column retains the original categorical info including the ordering")

The 'quartile' column retains the original categorical info including the ordering


#### Better performance with categoricals

In [92]:
n = 10_000_000

In [99]:
labels = pd.Series(['foo' , 'bar' , 'baz' , 'quz'] * int(n/4))

In [101]:
categories = labels.astype('category')

In [102]:
labels.memory_usage(deep = True)

520000132

In [103]:
categories.memory_usage(deep = True)

10000512

In [104]:
print('Categorical Significantly one fifth of defult string types')

Categorical Significantly one fifth of defult string types


In [105]:
%timeit labels.value_counts()

1.17 s ± 523 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [106]:
%timeit categories.value_counts()

54.3 ms ± 7.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Categorical Methods

In [107]:
s = pd.Series(['a' , 'b' , 'c' , 'd'] * 2)

In [111]:
cat_s = s.astype('category')

In [112]:
cat_s

,0
0,a
1,b
2,c
3,d
4,a
5,b
6,c
7,d


In [113]:
cat_s.cat.codes

,0
0,0
1,1
2,2
3,3
4,0
5,1
6,2
7,3


In [114]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [116]:
act_cat = ['a' , 'b' , 'c' , 'd' , 'e']

In [119]:
cat_s2 = cat_s.cat.set_categories(act_cat)

In [120]:
cat_s2

,0
0,a
1,b
2,c
3,d
4,a
5,b
6,c
7,d


In [122]:
cat_s2.value_counts()

,count
a,2
b,2
c,2
d,2
e,0


In [134]:
cat_s.value_counts()

,count
a,2
b,2
c,2
d,2


In [135]:
print('While the data look unchanged the new categories will be reflected in the operations that use them')

While the data look unchanged the new categories will be reflected in the operations that use them


In [137]:
cat_s3 = cat_s[cat_s.isin(['a' , 'b'])]

In [138]:
cat_s3

,0
0,a
1,b
4,a
5,b


In [140]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [143]:
cat_s3.cat.remove_unused_categories()

,0
0,a
1,b
4,a
5,b


In [144]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [147]:
cat_s3 = cat_s3.cat.add_categories('z')

In [148]:
cat_s3.cat.categories

Index(['a', 'b', 'c', 'd', 'z'], dtype='object')

In [151]:
cat_s3.cat.as_ordered()

,0
0,a
1,b
4,a
5,b


#### Creating Dummy Variable for modelling

In [152]:
cat_s = pd.Series(['a' , 'b' , 'c' , 'd'] * 2 , dtype = 'category')

In [153]:
pd.get_dummies(cat_s)

,a,b,c,d
0,True,False,False,False
1,False,True,False,False
2,False,False,True,False
3,False,False,False,True
4,True,False,False,False
5,False,True,False,False
6,False,False,True,False
7,False,False,False,True
